document.writeln("            <div id=\'bottom\' style=\'width:100%;height:149px;background:left top repeat rgb(245, 245, 245)\'>");
document.writeln("");
document.writeln("                <div id=\'pdv_17286\' class=\'pdv_class\' title=\'友情链接\' style=\'text-align: center;width:100%;height:31px;top:20px; z-index:19\'>");
document.writeln("");
document.writeln("                    <ul style=\'overflow:hidden;margin:0 auto;padding:0;text-align: center;display: inline-block\'>");
document.writeln("                        <span style=\'float:left;font-size:14px;font-weight:bold;line-height:32px;\'>友情链接：</span>");
document.writeln("");
document.writeln("                        <li style=\'list-style-type:none;float:left;margin:0px;padding-left:10px; white-space:nowrap\'>");
document.writeln("                            <a href=\'http://www.aliyun.com\' target=\'_self\' style=\'line-height:32px;\'>阿里云</a>");
document.writeln("                        </li>");
document.writeln("");
document.writeln("                        <li style=\'list-style-type:none;float:left;margin:0px;padding-left:10px; white-space:nowrap\'>");
document.writeln("                            <a href=\'http://www.alipay.com\' target=\'_self\' style=\'line-height:32px;\'>支付宝</a>");
document.writeln("                        </li>");
document.writeln("");
document.writeln("                        <li style=\'list-style-type:none;float:left;margin:0px;padding-left:10px; white-space:nowrap\'>");
document.writeln("                            <a href=\'http://www.100cm.cn\' target=\'_self\' style=\'line-height:32px;\'>草莓互联</a>");
document.writeln("                        </li>");
document.writeln("");
document.writeln("                        <li style=\'list-style-type:none;float:left;margin:0px;padding-left:10px; white-space:nowrap\'>");
document.writeln("                            <a href=\'http://www.weboss.hk\' target=\'_self\' style=\'line-height:32px;\'>网博士</a>");
document.writeln("                        </li>");
document.writeln("");
document.writeln("                        <li style=\'list-style-type:none;float:left;margin:0px;padding-left:10px; white-space:nowrap\'>");
document.writeln("                            <a href=\'http://www.tonv.cn\' target=\'_self\' style=\'line-height:32px;\'>同福信息科技</a>");
document.writeln("                        </li>");
document.writeln("");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div id=\'pdv_17287\' class=\'pdv_class\' title=\'脚注信息\' style=\'width:1200px;height:91px;top:56px;left:0px; z-index:20\'>");
document.writeln("                    <div id=\'spdv_17287\' class=\'pdv_bottom\' style=\'overflow:hidden;width:100%;height:100%\'>");
document.writeln("                        <div class=\'pdv_border\' style=\'border:0\'>");
document.writeln("                            <div style=\'width:100%;text-align:center;font:12px/20px Arial, Helvetica, sans-serif\'>");
document.writeln("                                <p style=\'text-align:center;\'>");
document.writeln("                                    <span style=\'color:#999999;line-height:2;\'>我的网站 版权所有 2008-2018 粤ICP备8888888</span>");
document.writeln("                                </p>");
document.writeln("                                <p style=\'text-align:center;\'>");
document.writeln("                                    <span style=\'color:#999999;line-height:2;\'>本页面内容为网站演示数据，前台页面内容都可以在后台修改。</span>");
document.writeln("                                </p>");
document.writeln("                                <div style=\'text-align:center;\'>");
document.writeln("                                    <span style=\'color:#999999;line-height:2;\'>Powered&nbsp;by&nbsp;weboss 2.12 &copy;2008-2018 www.weboss.hk</span>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");