
var myurl = 'http://admin.suzengguang.top';
document.writeln("<!DOCTYPE html>");
document.writeln("<html xmlns=\'http://www.w3.org/1999/xhtml\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta http-equiv=\'Content-Type\' content=\'text/html; charset=UTF-8\' />");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=11;IE=9;IE=8;IE=7\' />");
document.writeln("    <title>首页-企业形象成品网站</title>");
document.writeln("    <meta name=\'copyright\' content=\'2001-2016 Tonv Inc.\' />");
document.writeln("    <!-- <link rel=\'shortcut icon\' href=\'base/pics/favorite.ico\' /> -->");
document.writeln("    <link href=\'css/common_1.css\' rel=\'stylesheet\' type=\'text/css\' />");
document.writeln("    <link href=\'css/swiper.css\' rel=\'stylesheet\' type=\'text/css\' />");
document.writeln("    <link href=\'css/index.css\' rel=\'stylesheet\' type=\'text/css\' />");
document.writeln("    <script type=\'text/javascript\' src=\'js/base_1.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'js/form_1.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'js/blockui_1.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'js/jquery.superslide.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'js/jquery.w_1.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'js/switchable_v1.min_1.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'js/swiper.js\'></script>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body style=\'background:transparent\'>");
document.writeln("");
document.writeln("    <script>");
document.writeln("        var PDV_PAGEID = \'1\';");
document.writeln("        var PDV_RP = \'\';");
document.writeln("        var PDV_COLTYPE = \'index\';");
document.writeln("        var PDV_PAGENAME = \'index\';");
document.writeln("    </script>");
document.writeln("    <div id=\'page\' style=\'height: 100%;margin:auto;clear:both;overflow:hidden;position:relative;width:100%;\'>");
document.writeln("        <div id=\'contain\' style=\' background:transparent;margin:0px auto;padding:0px\'>");
document.writeln("                <div id=\'top\' style=\' height:60px;background:transparent;position: fixed;top: 0;width:1200px;left: 50%;margin-left: -600px;\'>");
document.writeln("                        <div style=\'margin:0 auto;position:relative;width:1200px;\'>");
document.writeln("                    <div id=\'pdv_17267\' class=\'pdv_class\' style=\'width:735px;height:61px;top:0px;left:461px; z-index:5\'>");
document.writeln("                        <div id=\'spdv_17267\' class=\'pdv_top\' style=\'overflow:inherit;width:100%;height:100%\'>");
document.writeln("                            <div class=\'pdv_border\' style=\'border:0\'>");
document.writeln("                                <link href=\'css/wumainmenu_1.css\' rel=\'stylesheet\' type=\'text/css\' />");
document.writeln("                                <style>");
document.writeln("                                    #pdv_17267 .wumainmenu {");
document.writeln("                                        padding-bottom: 1px;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 .bg {");
document.writeln("                                        _height: 65px;");
document.writeln("                                        background: #ffffff;");
document.writeln("                                        opacity: 1;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 .line {");
document.writeln("                                        background: #ffffff;");
document.writeln("                                        height: 1px;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 .bd {");
document.writeln("                                        height: 61px;");
document.writeln("                                        padding-left: 0;");
document.writeln("                                        padding-right: 0;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 ul {");
document.writeln("                                        height: 61px;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 dt {");
document.writeln("                                        height: 61px;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 li {");
document.writeln("                                        margin-right: 0;");
document.writeln("                                        width: 100px;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 dt a {");
document.writeln("                                        line-height: 65px;");
document.writeln("                                        background-color: transparent;");
document.writeln("                                        background-image: url();");
document.writeln("                                        color: #686868;");
document.writeln("                                        font-size: 14px;");
document.writeln("                                        font-weight: normal;");
document.writeln("                                        border-right-color: #ffffff;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 .cur dt a,");
document.writeln("                                    #pdv_17267 dt a:hover {");
document.writeln("                                        color: #ffffff;");
document.writeln("                                        background-color: #686868;");
document.writeln("                                        background-image: url();");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 dt a span {");
document.writeln("                                        line-height: 14px;");
document.writeln("                                        width: 100px;");
document.writeln("                                        color: ;");
document.writeln("                                        font-size: 12px;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 .cur dt a span,");
document.writeln("                                    #pdv_17267 dt a:hover span {");
document.writeln("                                        color: ;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 dd {");
document.writeln("                                        padding: 0 0;");
document.writeln("                                        width: 100px;");
document.writeln("                                        background: ;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 dd a {");
document.writeln("                                        line-height: 14px;");
document.writeln("                                        background: ;");
document.writeln("                                        background-image: url();");
document.writeln("                                        color: ;");
document.writeln("                                        font-size: 12px;");
document.writeln("                                        font-weight: normal;");
document.writeln("                                    }");
document.writeln("");
document.writeln("                                    #pdv_17267 dd a:hover {");
document.writeln("                                        color: ;");
document.writeln("                                        background: ;");
document.writeln("                                        background-image: url();");
document.writeln("                                    }");
document.writeln("                                </style>");
document.writeln("                                <div id=\'menumain\' class=\'wumainmenu wumainmenu-s1\'>");
document.writeln("                                    <div class=\'bg\'></div>");
document.writeln("                                    <div class=\'bd\'>");
document.writeln("                                        <ul>");
document.writeln("");
document.writeln("                                            <li class=\'n1 active\'>");
document.writeln("                                                <dl>");
document.writeln("                                                    <dt>");
document.writeln("                                                        <a href=\'首页.html\'>");
document.writeln("                                                            <span></span>网站首页</a>");
document.writeln("                                                    </dt>");
document.writeln("                                                    <dd></dd>");
document.writeln("                                                </dl>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <li class=\'n2\'>");
document.writeln("                                                <dl>");
document.writeln("                                                    <dt>");
document.writeln("                                                        <a href=\'gongsijianjie.html\'>");
document.writeln("                                                            <span></span>公司简介</a>");
document.writeln("                                                    </dt>");
document.writeln("                                                    <dd></dd>");
document.writeln("                                                </dl>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <li class=\'n3\'>");
document.writeln("                                                <dl>");
document.writeln("                                                    <dt>");
document.writeln("                                                        <a href=\'news.html\'>");
document.writeln("                                                            <span></span>新闻动态</a>");
document.writeln("                                                    </dt>");
document.writeln("                                                    <dd></dd>");
document.writeln("                                                </dl>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <li class=\'n4\'>");
document.writeln("                                                <dl>");
document.writeln("                                                    <dt>");
document.writeln("                                                        <a href=\'chanpin.html\'>");
document.writeln("                                                            <span></span>产品系列</a>");
document.writeln("                                                    </dt>");
document.writeln("                                                    <dd></dd>");
document.writeln("                                                </dl>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <li class=\'n5\'>");
document.writeln("                                                <dl>");
document.writeln("                                                    <dt>");
document.writeln("                                                        <a href=\'yewumoshi.html\'>");
document.writeln("                                                            <span></span>业务模式</a>");
document.writeln("                                                    </dt>");
document.writeln("                                                    <dd></dd>");
document.writeln("                                                </dl>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <li class=\'n6\'>");
document.writeln("                                                <dl>");
document.writeln("                                                    <dt>");
document.writeln("                                                        <a href=\'xiangmuanli.html\'>");
document.writeln("                                                            <span></span>项目案例</a>");
document.writeln("                                                    </dt>");
document.writeln("                                                    <dd></dd>");
document.writeln("                                                </dl>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                            <li class=\'n7\'>");
document.writeln("                                                <dl>");
document.writeln("                                                    <dt>");
document.writeln("                                                        <a href=\'lianxiwomen.html\'>");
document.writeln("                                                            <span></span>联系我们</a>");
document.writeln("                                                    </dt>");
document.writeln("                                                    <dd></dd>");
document.writeln("                                                </dl>");
document.writeln("                                            </li>");
document.writeln("");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                                <script>");
document.writeln("                                    $(function () {");
document.writeln("                                        $(\'#pdv_17267 dt a span\').each(function () {");
document.writeln("                                            var p = $(this).parent().position();");
document.writeln("                                            $(this).css(p);");
document.writeln("                                        });");
document.writeln("                                        $(\'#pdv_17267 .n\' + parseInt(\'0\')).addClass(\'cur\');");
document.writeln("                                        $(\'#pdv_17267 dd\').css(\'opacity\', \'0\');");
document.writeln("                                        if (\'0\' != 1) return;");
document.writeln("                                        $(\'#pdv_17267 dd\').each(function () {");
document.writeln("                                            if (this.innerHTML == \'\') $(this).remove();");
document.writeln("                                        });");
document.writeln("");
document.writeln("                                        if (getCookie(\'PLUSADMIN\') == \'SET\') {");
document.writeln("                                            return false");
document.writeln("                                        }");
document.writeln("");
document.writeln("                                        var plus = {};");
document.writeln("                                        var tm;");
document.writeln("                                        var cur;");
document.writeln("                                        for (var i in plus) {");
document.writeln("                                            plus[i] = $(\'#pdv_\' + plus[i]).size() ? $(\'#pdv_\' + plus[i]) : $(");
document.writeln("                                                \'.pdv_class[title=\' + plus[i] + \']\');");
document.writeln("                                            plus[i].hide().hover(function () {");
document.writeln("                                                clearTimeout(tm);");
document.writeln("                                                cur = this;");
document.writeln("                                            }, hide);");
document.writeln("                                            plus[i].children().removeClass(\'pdv_top\');");
document.writeln("                                        }");
document.writeln("");
document.writeln("                                        function hide() {");
document.writeln("                                            tm = setTimeout(function () {");
document.writeln("                                                $(cur).hide();");
document.writeln("                                            }, 500);");
document.writeln("                                        }");
document.writeln("                                        $(\'#pdv_17267 li\').hover(function () {");
document.writeln("                                            clearTimeout(tm);");
document.writeln("                                            $(cur).hide();");
document.writeln("                                            var i = $(this).index() + 1;");
document.writeln("                                            if (plus[i]) {");
document.writeln("                                                cur = plus[i].show();");
document.writeln("                                                return;");
document.writeln("                                            }");
document.writeln("                                            $(\'dd\', this).show();");
document.writeln("                                        }, function () {");
document.writeln("                                            hide();");
document.writeln("                                            $(\'dd\', this).hide();");
document.writeln("                                        });");
document.writeln("                                    })");
document.writeln("                                </script>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div style=\'margin:0 auto;position:relative;width:1200px;\'>");
document.writeln("                    <div id=\'pdv_17266\' class=\'pdv_class\' title=\'网站标志\' style=\'width:245px;height:50px;top:6px;left:0px; z-index:9\'>");
document.writeln("                        <div id=\'spdv_17266\' class=\'pdv_top\' style=\'overflow:hidden;width:100%;height:100%\'>");
document.writeln("                            <div class=\'pdv_border\' style=\'border:0\'>");
document.writeln("");
document.writeln("                                <a href=\'#\'>");
document.writeln("                                    <img src=\'picture/1513357730_1.jpg\' border=\'0\' />");
document.writeln("                                </a>");
document.writeln("");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("                <div class=\'lunbo\' style=\'width: 100%;margin: 0 auto;height:510px; \'>");
document.writeln("                      <!-- Swiper -->");
document.writeln("                        <div class=\'swiper-container\'>");
document.writeln("                                <div class=\'swiper-wrapper\'>");
document.writeln("                                <div class=\'swiper-slide\'><img src=\'picture/1499240939.jpg\' alt=\'\'></div>");
document.writeln("                                <div class=\'swiper-slide\'><img src=\'picture/1499240950.jpg\' alt=\'\'></div>");
document.writeln("                                <div class=\'swiper-slide\'><img src=\'picture/1499240957.jpg\' alt=\'\'></div>");
document.writeln("                                <div class=\'swiper-slide\'><img src=\'picture/1499243532.jpg\' alt=\'\'></div>");
document.writeln("                                <div class=\'swiper-slide\'><img src=\'picture/1499308301.jpg\' alt=\'\'></div>");
document.writeln("                                </div>");
document.writeln("                                <!-- Add Pagination -->");
document.writeln("                                <div class=\'swiper-pagination\'></div>");
document.writeln("                                <!-- Add Arrows -->");
document.writeln("                                <div class=\'swiper-button-next an swiper-button-black\'></div>");
document.writeln("                                <div class=\'swiper-button-prev an swiper-button-black\'></div>");
document.writeln("                            </div>");
document.writeln("                    <script>    ");
document.writeln("                    $(\'.lunbo\').mouseover(function(){");
document.writeln("                        $(\'.an\').css(\'opacity\',\'0.5\')");
document.writeln("                        $(\'.swiper-pagination\').css(\'opacity\',\'1\')");
document.writeln("                    })  ");
document.writeln("                    $(\'.lunbo\').mouseout(function(){");
document.writeln("                        $(\'.an\').css(\'opacity\',\'0\')");
document.writeln("                        $(\'.swiper-pagination\').css(\'opacity\',\'0\')");
document.writeln("                    })");
document.writeln("                    var swiper = new Swiper(\'.swiper-container\', {");
document.writeln("                            slidesPerView: 1,");
document.writeln("                            spaceBetween: 30,");
document.writeln("                            loop: true,");
document.writeln("                            pagination: {");
document.writeln("                              el: \'.swiper-pagination\',");
document.writeln("                              clickable: true,");
document.writeln("                              dynamicBullets: true,");
document.writeln("                            },");
document.writeln("                            navigation: {");
document.writeln("                              nextEl: \'.swiper-button-next\',");
document.writeln("                              prevEl: \'.swiper-button-prev\',");
document.writeln("                            },");
document.writeln("                            autoplay:true,");
document.writeln("                            effect : \'fade\',");
document.writeln("                          });");
document.writeln("                          </script>");
document.writeln("                </div>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");